version: 0.2
env:
  variables:
    AWS_REGION: "eu-central-1"
    LAMBDA_FUNC_NAME: [
      "arn:aws:lambda:eu-central-1:730335656503:function:APIService",
      "arn:aws:lambda:eu-central-1:730335656503:function:DataService"
    ]
phases:
  install:
    commands:
       - pip3 install boto3
  build:
    commands:
       - python3 lambda_from_github/update_lambda_functions.py