version: 0.2
env:
  variables:
    AWS_REGION: "eu-central-1"
#    LAMBDA_FUNC_NAME: "arn:aws:lambda:eu-central-1:730335656503:function:CfAPIServiceLambda"
    LAMBDA_FUNC_DIR: "api_service"
  parameter-store:
    LAMBDA_FUNC_NAME: "DataLambdaName"

phases:
  install:
    commands:
       - pip3 install boto3
  build:
    commands:
       - python3 update_lambda_functions.py