version: 0.2
env:
  variables:
    AWS_REGION: "eu-central-1"
    LAMBDA_FUNC_DIR: "data_service"
  parameter-store:
    LAMBDA_FUNC_NAME: "DataLambdaName"

phases:
  install:
    commands:
       - pip3 install boto3
  build:
    commands:
       - python3 update_lambda_functions.py